name: Update Contributors

on:
  pull_request:
    types: [closed] 
    branches:
      - main         

jobs:
  update-contributors:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Contributors Image
        run: curl -L https://contrib.rocks/image?repo=singhmonica1999/medianest > contributors.png

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add contributors.png
          git commit -m "Update contributors image after PR merge" || echo "No changes to commit"
          git push
